# permissions for end users to edit selectivedeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: selectivedeployment-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: edgenet
    app.kubernetes.io/part-of: edgenet
    app.kubernetes.io/managed-by: kustomize
  name: selectivedeployment-editor-role
rules:
- apiGroups:
  - deployments.edge-net.io
  resources:
  - selectivedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployments.edge-net.io
  resources:
  - selectivedeployments/status
  verbs:
  - get
