# permissions for end users to view subnamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: subnamespace-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: edgenet
    app.kubernetes.io/part-of: edgenet
    app.kubernetes.io/managed-by: kustomize
  name: subnamespace-viewer-role
rules:
- apiGroups:
  - multitenancy.edge-net.io
  resources:
  - subnamespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multitenancy.edge-net.io
  resources:
  - subnamespaces/status
  verbs:
  - get
