# permissions for end users to view tenants.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tenant-admin-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: edgenet
    app.kubernetes.io/part-of: edgenet
    app.kubernetes.io/managed-by: kustomize
    edge-net.io/generated: "true"
  name: edgenet:tenant-admin
rules:
- apiGroups:
  - core.edgenet.io
  resources:
  - subnamespaces
  - sliceclaims
  verbs:
  - '*'
- apiGroups:
  - core.edgenet.io
  resources:
  - subnamespaces/status
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.edgenet.io
  resources:
  - selectivedeployments
  verbs:
  - '*'
- apiGroups:
  - registration.edgenet.io
  resources:
  - rolerequests
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - persistentvolumeclaims
  - pods
  - pods/exec
  - pods/log
  - pods/attach
  - pods/portforward
  - replicationcontrollers
  - services
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - ingresses
  - networkpolicies
  - replicasets
  - replicationcontrollers
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  - networkpolicies
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  - controllerrevisions
  verbs:
  - get
  - list
  - watch
