# Copyright 2021 Contributors to the EdgeNet project.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nodecontributions.core.edgenet.io
spec:
  group: core.edgenet.io
  versions:
    - name: v1alpha
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Address
          type: string
          jsonPath: .spec.host
        - name: VPN-Address-V4
          type: string
          jsonPath: .spec.vpn.addressV4
        - name: VPN-Address-V6
          type: string
          jsonPath: .spec.vpn.addressV6
        - name: SSH-Port
          type: integer
          jsonPath: .spec.ssh.port
        - name: Enabled
          type: boolean
          jsonPath: .spec.enabled
        - name: Status
          type: string
          jsonPath: .status.state
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - enabled
                - host
                - ssh
              properties:
                enabled:
                  type: boolean
                tenant:
                  type: string
                  nullable: true
                  pattern: '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'
                host:
                  type: string
                  description: the node IP address to be used by Kubernetes and SSH.
                ssh:
                  type: object
                  properties:
                    port:
                      type: integer
                      minimum: 1
                    user:
                      type: string
                vpn:
                  type: object
                  nullable: true
                  properties:
                    addressV4:
                      type: string
                      pattern: '^[0-9.]+$'
                      nullable: true
                      description: the IPv4 address assigned to the node's VPN interface.
                    addressV6:
                      type: string
                      pattern: '^[a-f0-9:]+$'
                      nullable: true
                      description: the IPv6 address assigned to the node's VPN interface.
                    endpointAddress:
                      type: string
                      pattern: '^[a-f0-9.:]+$'
                      nullable: true
                      description: the public IPv4/v6 address of the node.
                    endpointPort:
                      type: integer
                      minimum: 1
                      nullable: true
                      description: the port on which WireGuard is listening.
                    publicKey:
                      type: string
                      description: the WireGuard public key of the node's VPN interface (Base64 encoded).
                limitations:
                  type: array
                  nullable: true
                  items:
                    type: object
                    properties:
                      kind:
                        type: string
                        enum:
                          - Tenant
                          - Namespace
                      identifier:
                        type: string
                        pattern: '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'
            status:
              type: object
              properties:
                state:
                  type: string
                message:
                  type: array
                  nullable: true
                  items:
                    type: string
  scope: Cluster
  names:
    plural: nodecontributions
    singular: nodecontribution
    kind: NodeContribution
    shortNames:
      - nc
