apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: edgenet-system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: edgenet
    app.kubernetes.io/part-of: edgenet
    app.kubernetes.io/managed-by: kustomize
  name: edgenet-system
